### ISSUE TITLE
Recommended feature

### ISSUE THREAD

**Issue by nodog445** [YarosMallorca/DJI-Mapper#1]
Hi,

It would be useful if you could chose the direction the lines are created in (north-south / east-west)
Also an option to create a grid pattern survey.

Satellite would also be extremely useful.

Thanks #

**Comment by YarosMallorca** [comment]
The direction can be controlled by the "Angle" option in the Aircraft tab.

<img src="https://github.com/user-attachments/assets/aece5d91-9ddd-4326-8f87-7ee4af592a04" height="200px" />

The satellite option is not yet available but I will implement it soon!

**Comment by nodog445** [comment]
Ok great! Sorry l assumed this field was the gimbal angle for some reason, looking forward to seeing new features released!

**Comment by YarosMallorca** [comment]
@nodog445 the gimbal angle is set in the Camera tab 😉 maybe I have to make that more clear in the documentation.
