### ISSUE TITLE
Installation problem on corporate pc

### ISSUE THREAD

**Issue by APOS80** [YarosMallorca/DJI-Mapper#12]
Hello

My corporate laptop is restricted to software with an installer so i can not run software just from an exe file.

Would it be possible to make an installer for windows?

**Comment by YarosMallorca** [comment]
It is possible to make one using Inno Setup Installer.
However as a workaround, try using the web version of the software for now: https://djimapper.yarosfpv.com

**Comment by APOS80** [comment]
Looks nice!

The only thing i miss is the double grid.
