### ISSUE TITLE
Add Air 2S support 

### ISSUE THREAD

**Issue by Cagier** [YarosMallorca/DJI-Mapper#18]
Is there a technical reason that this cannot work with the Air 2S? I do some programming so if I can help with analysing the file structure or beta testing anything then please let me know. 
Thanks

**Comment by YarosMallorca** [comment]
The Air 2S doesn't have native waypoint integration from DJI, but there is the SDK, so you can use DJI Mapper to generate the mission, export it to Litchi, and run it through there.

Litchi is not maintained by me and is paid software. DJI Mapper supports exporting to a CSV file that can be read by Litchi Mission Hub.
