### ISSUE TITLE
Feature Request - Image Numbers and Flight Direction 

### ISSUE THREAD

**Issue by nW70M1** [YarosMallorca/DJI-Mapper#3]
Could you add numbers to the camera points and possibly make the camera symbols directional or add arrows for flight direction along the route lines to help make the flight direction more obvious.

**Comment by YarosMallorca** [comment]
Thanks, I will look into this when I have time, I agree this would definitely be nice :)

**Comment by YarosMallorca** [comment]
This may be worked on later in the project, I'll prioritize other features for now.
Thanks for your suggestion!
