### ISSUE TITLE
Feature Request - Save and Load Area of Interest

### ISSUE THREAD

**Issue by nW70M1** [YarosMallorca/DJI-Mapper#4]
Could you make it possible to export and import project areas from saved data in a format such as KMZ.

You are already exporting DJI flavoured KMZ data from the app so maybe you could make it possible to optionally export the project area as a separate regular KMZ when exporting the survey mission so it can be reloaded later or other sourced KMZ can be loaded.

**Comment by jasonrmh** [comment]
+1 for this.
If we could import a kml polygon to use as a mapping boundary that would save time on planning 🙏

**Comment by YarosMallorca** [comment]
Implemented in 62ccd5146989f492ea5c3ed6ac4fcbe1b644e2b2
It will be present in the next release
