### ISSUE TITLE
Camera Preset - Focal Length Restricted to 1 decimal place

### ISSUE THREAD

**Issue by jasonrmh** [YarosMallorca/DJI-Mapper#6]
When adding a custom camera preset, the focal length is restricted to 1 decimal place.
eg. if I want to add a focal length of 6.65mm, I can only set 6.6

There also seems to be an issue with saving a new camera preset.
As there is no explicit save button, if I enter a new preset then swith to an existing preset, then switch back to my new custo preset, the values are not saved.

However, if I then delete the custom preset, it remains in the list and the values are correct 🥴

**Comment by YarosMallorca** [comment]
@jasonrmh Thanks for the report, will look into it soon.

**Comment by YarosMallorca** [comment]
@jasonrmh I have fixed this issue in code, this will be rolled out soon in V1.3.0
