### ISSUE TITLE
Feature Request - Margin

### ISSUE THREAD

**Issue by jasonrmh** [YarosMallorca/DJI-Mapper#7]
It would be useful to have a 'margin' parameter which defaults to 0m but can be used to overfly the defined boundary by the set distance.
This is a useful feature to ensure the set boundary is fully captured.

**Comment by YarosMallorca** [comment]
@jasonrmh Margin in what direction? To reduce the flyable area, or increase it?

**Comment by jasonrmh** [comment]
To increase.
Eg. Entering a margin of 10m means the flight path would extend over the set boundary by 10m, in all directions.

**Comment by YarosMallorca** [comment]
Isn't it easier to just increase the flyable area by selecting a larger portion of the map?

For now this won't be worked on, will get back to this after fixing more crucial issues.

**Comment by jasonrmh** [comment]
Agreed not critical when manually drawing a boundary, but if [boundary import](https://github.com/YarosMallorca/DJI-Mapper/issues/4) is implemented, the margin feature will be useful to ensure the entire extent of the boundary is covered in good quality (data at the edge of the mapping boundary tends to suffer).
